DIR=/home/andrea/checkpoint

start() {
    "$DIR"/ML-Restart/singularity/checkpoint.sh start "$@"
}

stop() {
    "$DIR"/ML-Restart/singularity/checkpoint.sh stop "$@"
}

resume() {
    "$DIR"/ML-Restart/singularity/checkpoint.sh resume "$@"
}
